package com.company;

public class MT_114 {
    public static void main(String[] args) {

        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '
        //error: failed to push some refs to '

        

    }
}
